social_auth_microsoft.settings:
  type: config_object
  label: 'Social Auth Microsoft settings'
  mapping:
    app_id:
      type: string
      label: 'Application ID'
    app_secret:
      type: string
      label: 'Application Secret'
